if(NOT TARGET MVS::MVS)
  add_library(MVS::MVS SHARED IMPORTED)
  set_target_properties(MVS::MVS PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/inc"
    IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/lib/libgxiapi.so"
    IMPORTED_NO_SONAME TRUE
  )
endif()
